name: build

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: setup go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.22'
      - name: unit tests
        run: go test -v -cover ./...
      - name: build binaries
        run: |
          go build -o bin/tq main.go
          go build -o bin/json2jq extras/tf2json/tf2json.go
          go build -o bin/json2jq extras/json2tf/json2tf.go
